# https://wandb.ai

wandb:
  _target_: pytorch_lightning.loggers.wandb.WandbLogger
  project: elsa
  id: ${oc.select:name}
  name: ${datamodule.dataset_name}-${model_name}-${loggers.wandb.id}
  save_dir: ${paths.wandb_dir}
  mode: online
  log_model: False