# https://wandb.ai

wandb:
  _target_: pytorch_lightning.loggers.wandb.WandbLogger
  project: elsa
  name: ${datamodule.dataset_name}-${model_name}-${eval:"'-'.join([t for t in ${tags}])"}
  save_dir: ${paths.wandb_dir}
  id: sdfjiwkl
  mode: online
  log_model: False