# @package _global_

default_mode: True

hydra:
  # default output paths for all file logs
  run:
    dir: ${oc.env:RESULT_DIR,${paths.log_dir}}/runs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ${oc.env:RESULT_DIR,${paths.log_dir}}/multiruns/${now:%Y-%m-%d_%H-%M-%S}
    subdir: ${hydra.job.num}