
watch_model:
  _target_: src.callbacks.wandb.WatchModel
  log: all
  log_freq: 100

upload_code:
  _target_: src.callbacks.wandb.UploadCodeAsArtifact
  code_dir: ${paths.root_dir}/src

# PL learning rate monitor callback requires a logger
learning_rate_monitor:
  _target_: pytorch_lightning.callbacks.LearningRateMonitor
  logging_interval: step