# @package _global_
defaults:
  - _self_
  - paths: default
  - mode: default
  - trainer: default
  - optimizer: adamw
  - scheduler: null
  - task: sequence-model
  - model: null
  - datamodule: null
  - callbacks: default
  - loggers: null
  - metrics: null
  - experiment: null

  # enable colorlog
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog

print_config: True
#override hydra/job_logging/handlers/file/filename: ${hydra:runtime.output_dir}/${hydra.job.name}.log

# tags of experiment run
# used as identifiers to checkpoints
tags: []

# resume from checkpoint
resume: False